services:
  analysis-db:
    image: postgres:latest
    container_name: analysis-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: analysis-example
    ports:
      - "5432:5432"
    volumes:
      - analysis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  analysis_data:
